<!-- Modal Structure -->
<div id="temps" class="modal">
			<div class="modal-content">
			  <h4>Temps</h4>
			  
			  <p>« Chez les <b>CIVILISÉS</b>, je l’ai dit, nous avons le Temps. Le Temps convient à l’humanité <b>Spiritualiste</b>, à la société Propriétaire-Citoyenne, <b>Marchande</b>. Ce monde de <b>Liberté</b> est Humaniste, Moraliste-Légaliste-Politique ; il est aussi Progressiste, c’est-à-dire Réformiste-Révolutionnaire. La mentalité civilisée ne connaît que des “<b>êtres</b>” particuliers-généraux : une société de Personnes combinée à un système de Choses ; ayant pour principe l’Être suprême, le Sujet absolu (<b>Créateur</b> et Mystère). C’est dans ce contexte que l’on a le <b>Temps</b>, essentiellement Discret-Continu, <b>Linéaire</b> (téléologique-archéologique). La pensée qui correspond à ce temps est Dogmatique-Rationnelle-Intellectualiste.</p>
<p>(...)</p>
<p>Le civilisé, c’est-à-dire le bourgeois, dit : “Il faut être AVARE DE SON TEMPS” ; chose absolument inconcevable par le cerveau collectif des primitifs. »</p>

<p>__________________________</p>


			
				  <p>Voir <a href="https://www.eglise-realiste.org/pdf/Hebreux_ed.pdf" target="_blank"> "Les Hébreux, Peuple de l'échec?"</a>, p.10 - Talib Freddy - Eglise Réaliste Mondiale - octobre 2003 - Editions de l'Evidence - 2010</p>
				  <p>__________________________</p>
				 
<p>Qu’est la religion Orthodoxe Parfaite ? <b>Superficiellement</b>, c’est la Religion qui paraît, comme le fruit d’une <b>Révolution</b>-Réformatrice qui la purifie, et se donne comme la “vraie” religion, celle qui “aurait dû être” depuis toujours, n’eut été l’antique penchant au Mal <b>prédominant</b> en l’homme civilisé. Nous voilà donc arrivés <b>au “milieu du Temps”</b> : Adam régénéré à présent en PRINCIPE, il ne suffit plus que de faire passer cela dans les FAITS, par une longue marche strictement <b>Réformatrice</b>-Révolutionnaire. Ainsi, à partir d’un noyau de Vraie Église, nous allons évangéliser les nations, édifier laborieusement l’Église Mondiale réelle. La <b>prédication</b> de la vraie Foi ralliera assurément la Raison éclairée. Les vrais croyants vaincront, malgré les tribulations qu’ils supporteront de manière rigoureusement <b>Défensive</b>, que susciteront les païens endurcis, cherchant à manipuler les simples fidèles attachés à des <b>Préjugés</b> superstitieux, entachés d’idolâtrie. Enfin, l’Église Mondiale étant établie pour l’essentiel, Dieu viendra “achever nos efforts” (Kant), et opérer SA <b>Révolution-Révolutionnaire</b>, dire : “Cette fois je rénove tout, je fais un Ciel nouveau et une nouvelle Terre.” (Apoc. 21 : 1-5).</p>
<p>Pourquoi cette version est-elle superficielle ? Parce qu’on la répétait – sous des formes plus ou moins conséquentes – à chaque Révolution Réformatrice. Or, cette fois, on est absolument conséquent, <b>c’est bien</b> la Religion Parfaite qui est produite, et de façon tout à fait Orthodoxe. Et c’est ce qui fait le Drame de la Religion Parfaite. Kant a bel et bien le projet de mettre sur pied la Vraie Église à vocation Mondiale : c’est “<b>l’Association Morale civile à mission Cosmopolite*</b>”, constituée “exclusivement en vue du Bien”, ne connaissant que la Loi suprême d’être “agréable à Dieu”. Elle déclare donc tout net <b>ne pas se référer au</b> “<b>Peuple Souverain</b>”, ce qui reviendrait à professer la Divinité du Peuple. L’objet de l’Église est de “<b>faire un Peuple de Dieu</b>”. La Souveraineté du Peuple, en revanche, doit valoir sans réserve en ce qui concerne les Associations Politiques, le Droit ; le Prince devant se reconnaître comme simple “1er serviteur de l’État”. Chacun son domaine. LES Princes découvriront tout l’avantage de protéger LA vraie Église qui fera s’éteindre les “religions impures” d’hier, et qui ne peut avouer dans cette mission qu’un tout autre “prince”, Dieu lui-même.</p>
<p>Pourquoi ce plan, qui décide que le vrai <b>DÉBUT</b> de la Religion Pure commence, que celle-ci n’aura qu’une stricte Réforme à développer, plan rigoureusement Orthodoxe dans la forme, et justifié par la Perfection <b>atteinte</b> de la civilisation, coïncide-t-il avec le Drame de la Religion ? Tout simplement parce que le vrai Épanouissement de la religion que propose Kant, légitime en PRINCIPE, ne peut que faire qu’un avec l’Extinction de la religion <b>historique</b> en FAIT. Kant sanctionne le fait que la religion parfaite, avec la civilisation parfaite, arrive à son Terme, mais se voit simultanément avec la MOITIÉ du Temps ouverte devant lui. Ceci est inévitable, selon l’authentique Orthodoxie qui voit la religion comme seule mentalité valable pour TOUT le Temps ; et pourtant cette stricte Orthodoxie se trouve devant une <b>impossibilité historique</b>. Si on laissait faire Kant, sa vraie Religion amènerait l’humanité sur le seuil d’une toute autre Révolution Révolutionnaire que celle qu’il envisage à la Plénitude des Temps : celle du Comm-Anar, qui n’est qu’historique. Personne ne COMPREND l’impossibilité du programme de Kant, puisque tous sont comme lui enfermés dans l’horizon civilisé ; mais, sous la pression de l’histoire réelle, tous l’abandonnent, à commencer par son meilleur disciple, Fichte, qui se lance dans sa “Théorie de la Science” dès 1794. <b>Il n’y aura pas d’Église Parfaite</b>.</p>
<p>Ce n’est pourtant pas pour rien qu’on nommera Kant “<b>le Philosophe de la Révolution Française</b>” ! <b>Sieyès</b> aussi pensait que le Tiers-État au pouvoir aurait pour tâche d’éduquer la masse des Citoyens PASSIFS afin qu’ils deviennent ACTIFS. Et la <b>pensée</b> de Sieyès, avec celle de son contraire identique <b>Marat</b>, plane sur toute la Révolution (1789-1805), comme l’<b>action</b> de <b>Robespierre</b> et <b>Napoléon</b> domine cette Révolution. C’est ainsi que la Révolution fut fille de Kant… en désordre ! (l’histoire réelle ne se déroule pas comme dans un livre).</p>
<p>Marx et Engels disent dans l’Anti-Dühring (1877) : “le système de Hegel fut un <b>colossal avortement</b>”. Ils ne prennent pas la chose d’assez haut ; c’est à propos de Kant qu’on doit le dire. C’est là qu’il y a du “<b>colossal</b>”, car après lui il n’y eut qu’un seul problème théorique qu’on ne parvint jamais à résoudre : comment dépasser Kant ? Ce fut d’ailleurs l’écueil immédiat de Fichte puis de Hegel, chacun ayant successivement (et en sens inverse : Sensualiste puis Spéculatif) cette prétention, et ne faisant que s’engouffrer dans l’<b>Hétérodoxie</b> panthéiste. Quant au côté “<b>avortement</b>”, il faut distinguer. Recevoir le titre de philosophe de la Révolution est un glorieux avortement. Avortement quand même, puisque la Révolution ne dura <b>que 16 ans</b>, et non la Moitié du Temps ; et parce que son esprit ne survécut pas à la période étroitement <b>Révolutionnaire</b>, alors qu’il se proposait pour une demi-perpétuité étroitement Réformatrice.</p>				

<p>__________________________</p>


			
				  <p>Voir <a href="https://www.eglise-realiste.org/pdf/Drame_Religion_Parfaite_ed.pdf" target="_blank"> "Le Drame de la Religion Pafaite?"</a>, p.4-5-6 - Freddy Malot - mars 2006 - Eglise Réaliste Mondiale - Editions de l'Evidence - 2010</p>



			</div>
			<div class="modal-footer">
			  <a href="#!" class="modal-close waves-effect waves-green btn-flat">Vu</a>
			</div>
		  </div>