<!-- Modal Structure -->
<div id="volontariat-gratuite" class="modal">
			<div class="modal-content">
			  <h4>Volontariat Gratuité</h4>
			  
			  <p>« Il n’est de société possible, succédant à la société Préhistorique, que le Comm-Anar dont “l’Économie” a pour principe <b>Volontariat-Gratuité</b>. C’est-à-dire ?</p>
			  <p style="text-align:center;"><b>•••</b></p>

<p>Pour un Utopiste, Volontariat-Gratuité est un idéal absolument limpide : je veux une “économie” SANS ARGENT. Cette limpidité est trompeuse. Pourquoi ? Parce que “économie sans argent” veut dire économie <b>non-civilisée</b>, sans Marché. Au vrai sens des mots, on veut donc dire : une économie sans économie ! L’économe est le MÉNAGER, celui qui gère la MAISON (OIKON = VICUM en grec = village). Le Comm-Anar n’a rien à voir avec cela, puisqu’il n’est pas non-civilisé, mais <b>non-préhistorique</b>. »</p>
<p>__________________________</p>

				  

				  <p>Voir <a href="https://www.eglise-realiste.org/pdf/Volontariat_Gratuite_ed.pdf" target="_blank"> "Volontariat-Gratuité"</a>, p.1 - Talib Freddy - août 2005</p>

				  <p>__________________________</p>

				  <p>La masse des producteurs “hérite” de <b>la Liberté</b> des anciens maîtres (patrons). Ceci veut dire avant tout que CHACUN des producteurs se trouve désormais comme “à son compte”, et dès lors comme “exposé à la faillite”. Notons bien que ce n’est plus en tant que chef d’une “cellule” sociale dénommée entreprise, mais personnellement. En effet, le Comm-Anar fait pour la première fois une réalité de la fameuse “personne humaine”, qui ne désignait auparavant que l’âme et ne concernait que les moeurs. Notre “entrepreneur” du Comm-Anar n’a évidemment besoin de nuls “stimulants”. Surtout pas de stimulants “matériels” : on n’a jamais parlé de cela qu’à l’intention des esclaves ! Quant au stimulant “moral”, il n’a rien d’“altruiste” : il se trouve dans la propre satisfaction accompagnant l’accomplissement de la tâche qu’il s’est lui-même imposée.</p>
				  <p>(...)</p>
				  <p>la Planification du Comm-Anar se fait essentiellement “en nature” (on dit aussi en volume), avec pour critère déterminant <b>l’Utilité</b> (valeur d’usage), et qu’elle s’établit essentiellement “à partir du bas”, depuis l’usage raisonné que l’Individu décide de faire de ses <b>Capacités</b>. Que devient la Valeur, qui était l’expression “économique” même de la Liberté. Napoléon disait aux patrons : “la Consommation doit toujours être la règle du Commerce”. On peut encore transposer ! (Notons que, “paradoxalement”, nous avons plus à tirer pour NOTRE Liberté de l’école Administrative que de l’école Libérale, plus de Ferrier que de Ricardo). On produit essentiellement “SUR COMMANDE”, se proposant des objectifs qualitatifs (exemple de l’anti-Haussmann : éventrer une ville pour y introduire la campagne). Ceci élimine le problème des “débouchés”, l’épée de Damoclès de la demande “solvable”. Mais ceci n’a de sens <b>que si</b> lesdits objectifs sont fixés à partir de ce que permet l“offre” disponible de travail libre, volontaire, et la “productivité” à attendre de ce travail libre. Ceci se “calcule” à partir de ce que l’expérience a prouvé durant une série d’exercices antérieurs : on sait ce que les nouveaux “patrons” sont capables d’accomplir dans les divers domaines et, en moyenne, tous domaines confondus. Et les nouveaux patrons, motivés avant tout par la possibilité offerte de la révélation de leurs capacités et de l’efficacité de celles-ci, combinées à celles de leurs co-associés dans la République Syndicale, au service finalement de l’Humanité entière et de l’Histoire, ne voient dans leur “rémunération” qu’un salaire “DE LUXE”, secondaire, comme l’“argent de poche” d’un adolescent, ou les “fantaisies” que la situation du ménage permet à la femme au foyer de s’offrir. Toutes les constructions “économiques” élaborées à partir de l’esclavage bourgeois s’écroulent : “normes” de production, “grilles” de salaires, “à chacun selon son travail”, etc. Est-ce qu’un patron d’hier s’appliquait ces critères ? Et encore moins un Saint Bernard, un Richelieu ou un Lénine ?</p>
<p>(...)</p>
<p>La masse des producteurs du Comm-Anar ne fait pas qu’hériter de la Liberté des anciens maîtres ; elle découvre et fait rayonner la Liberté complémentaire de <b>la Nature</b>, fondamentalement identique à celle de l’Humanité. Les gens du Comm-Anar expérimentent cette Liberté de la Nature dans leur propre corps, depuis ses cinq sens périphériques jusqu’en son centre cérébral. Cette Liberté de la Nature est la seule NÉCESSITÉ qu’ils reconnaissent ; et non plus la contrainte de la loi de la Valeur sur le Marché, ou la force coercitive de la Loi exercée par l’État. Et c’est la seule prise en compte de cette nécessité, avec toutes ses conséquences qui fonde leur Liberté ; car de là vient la primauté accordée à <b>l’Utilité</b> des produits et aux <b>Capacités</b> dans le travail.</b>
Pensons qu’il ne pouvait qu’en être ainsi avec le Comm-Anar, puisque l’ancienne Physique parvient avec les Modernes à ramener les QUALITÉS des corps saisies par nos SENS corporels à des “intensités” mesurables. Cette nouveauté envahit spectaculairement la physique avec l’immense Mathématicien et Physicien Christian HUYGENS de La Haye, nourri de Descartes, et que Newton nomma : “le Souverain Huygens”. Notre protestant (que Colbert pensionne à Paris en 1665) fuit la France en 1681, dès avant la révocation officielle de l’Édit de Nantes (1685), scandalisé par la barbarie du vieux roi-soleil et son acolyte Bossuet. L’oeuvre de Huygens (1629-1695) brille de 1660 à 1690. Elle porte sur le couple : Élasticité des CORPS / Ondes du MILIEU, en lequel se concentre l’“invraisemblable” mécanique de la qualité physique. Toutes les divagations barbares ultérieures – de la Relativité et des Quanta – viennent de l’impuissance à dépasser Huygens et ses disciples à propos de la lumière, l’électricité, le magnétisme et la radioactivité : bref, à propos de tout ce qui touche à l’ancien “éther” (milieu) et la spontanéité physique traduite par les sens (toucher, goût, odorat, ouie, vue) et les qualités objectives correspondantes (corps). Finalement, on n’alla pas plus loin à ce sujet que ce que disait la “force élastique” et les “longueurs d’ondes” (les “corps durs” d’une part, et l’“ébranlement” de leurs milieux d’autre part).</p>
<p>(...)</p>
<p>Qu’est donc, finalement, l’“économie” du Comm-Anar ?</p>
<p>Ce n’est plus, à proprement parler, une économie, ce mot faisant invinciblement penser au couple contradictoire économie-politique de la pratique sociale civilisée, opposant propriétaires et fonctionnaires (fonctionnaire doit être pris au sens des “magistrats” de la société Politique ; rien à voir avec le sens actuel que prend le mot dans notre Parasitisme affecté du cancer de l’État-patron). Le Comm-Anar, justement, ne connaît qu’une <b>PRATIQUE</b> sociale <b>directe</b>, qui confond produits et services, propriétaires et fonctionnaires. Je parle de pratique “directe” en pensant à la rubrique “Action” du tableau “Travail Civilisé”, laissant donc de côté ce qui relevait de la “Science” dans la société Politique. Bref, les “praticiens” du Comm-Anar sont propriétaires-magistrats.</b>
<p>À partir de quoi notre Pratique Directe s’organise-t-elle ? À partir du fait que <b>le Monde</b> (Nature-Humanité) ne se distingue de <b>la Réalité</b> (Matière-Esprit) que par le fait qu’il est la Réalité en tant que donnant prise à la Pratique (alors que la Réalité au sens étroit est saisissable seulement par la Théorie : l’immuable constamment différent de façon absolue et non pas de façon relative. Bref, le Monde “est” la Réalité “en dernière analyse”. C’est l’auxiliaire ÊTRE qui peut nous égarer !) Ensuite, le Monde pris à part est fondamentalement “UN”, ce n’est que par l’abstraction qu’on le dédouble en Nature-Humanité, de sorte que cette différence mise à jour n’est que relative et, pour cela, ne doit être vue que comme un RAPPORT : les pôles ne sont ni antagoniques, ni hégémoniques en un sens ou l’autre ; ils sont identiques “en dernière analyse”. Nous ne sommes plus dans la Préhistoire : on peut dire <b>Nature</b> = Pensée inconsciente, et non pas Vie comme dans la société Parentale ; et <b>Humanité</b> = Vie consciente, et non pas Esprit comme dans la société Politique.</b>
<p>Ceci dit, le Comm-Anar va Planifier la Pratique Directe. Comment ? On se trouve toujours dans une situation particulière du rapport Humanité-Nature. C’est de façon concrète que ces deux Libertés – qui peuvent être dites tout autant deux Nécessités – se conjuguent. On ne peut pas se proposer une combinaison Moyens-Besoins en l’air. À chaque étape il y a simplement une exigence désirable à satisfaire (on ne peut même pas dire que demain doit être ou sera “meilleur” qu’hier, car demain aura SON problème). Aujourd’hui, on se donne néanmoins un <b>Plan à exécuter</b>, qu’on dit possible par rapport au passé, et souhaitable par rapport à l’avenir. Ainsi, si je meurs dans l’exécution consciencieuse de ce plan, ma vie sera bien remplie, sans égard à un quelconque “demain”. En ce sens, le plan en cours est “a posteriori” parce qu’il tient compte des conditions, mais “indicatif” parce que c’est “au pied du mur qu’on voit le maçon”. Il est aussi “a priori” parce qu’il porte sur les “vrais besoins” d’hommes libres, mais “impératif” parce que les gens du Comm-Anar ne sont pas de ceux “qui disent et ne font pas”. Tout cela pour dire que notre planification ne se conçoit qu’“en nature” ; elle met en jeu de libres Capacités visant de nécessaires Utilités.</p>
<p>La Richesse objective est Don-Valeur. Don parce que dépendante de la “pensée inconsciente” de la Nature ; Valeur parce que fruit de la “vie consciente” de l’Humanité. Quelle est la <b>Rémunération des hommes</b> ? Il faut distinguer. Si je plante un arbre, je jouis de cette richesse mais non de façon exclusive, sauf la satisfaction d’en avoir été l’auteur direct qui est ma rémunération PRINCIPALE. Il y a, à côté de cela, ma rémunération ACCESSOIRE, “exclusive”, mais faite de seules Utilités comme le reste de la Richesse. Cette rémunération Accessoire est fondamentalement “gratuite”, comme la Principale. La fixation du rapport Principal-Accessoire de la rémunération fait partie de la Planification. La part Accessoire de la rémunération est gratuite à la source, car soustraite globalement, pour la population entière des propriétaires-magistrats, de la richesse générale déterminée en Don-Valeur, en fonction des “vrais besoins” d’hommes libres. Quant à l’affectation “finale” aux individus, c’est l’affaire de jurys constitués par les propriétaires-magistrats eux-mêmes statuant sur leur contribution mutuelle, appréciant le degré de “vie CONSCIENTE” que les uns et les autres ont montré relativement. D’où l’utilité de BONS nominatifs fixant la quote-part offerte à chacun dans la répartition de l’Accessoire global. Le critère de la conscience vitale n’a plus rien à voir avec les vieilles distinctions en travail simple et travail complexe, en manuels et intellectuels. Rappelons que l’on a désormais des Patrons qui <b>SE</b> donnent des salaires “de luxe”, se répartissent des Dons Mérités. Celui qui reçoit “moins” de bons que d’autres s’est lui-même attribué cette part d’accessoire. Il ne s’attend pas à la sécurité du “bol de fer” d’un fonctionnaire “communiste” ; il n’est plus cependant soumis à la “discipline” de la faim de l’esclave civilisé. Libre à lui de mieux déployer ses capacités, autrement ou ailleurs, de voyager ou de se contenter de sa “médiocrité dorée” pour s’offrir des loisirs qu’il occupera comme il l’entend, peut-être au plus grand avantage commun (à la surprise de ses congénères !), toujours sans craindre d’être “jeté à la rue”.</p>
<p>À quoi le Praticien du Comm-Anar consacre-t-il son temps ? Il faut y revenir : avant tout à <b>démolir la vieille Technique</b> ! Pas de renversement du travail en valeur sans cela (celui du maître comme celui de l’esclave). Pour ce faire, il faut avoir en tête le tableau complet de la Physique moderne gouvernée par le Mécanisme, de l’Astronomie à la Médecine (les juifs de Septimanie excellaient dans ces deux disciplines réunies en même temps qu’en “philosophie”). Il faut en particulier sortir enfin de l’ornière barbare où se trouve la médecine, écartelée entre une allopathie dégénérée et criminelle et une homéopathie utopico-occultiste (c’est Hahnemann qui fonda l’homéopathie en 1810). Pénétré de ce tableau, chacun dans son domaine recherche sans cesse ce que cela donne en substituant le Dynamisme au mécanisme, et les conséquences que cela entraîne dans la Technique. De temps à autre, des congrès de “nouveaux ingénieurs” confrontent leurs expériences, ne s’étant pas privés de demander conseil aux “sauvages” et aux enfants.</p>
<p>C’est alors que supprimer l’“antagonisme (!) entre les Manuels et les Intellectuels” deviendra une affaire sérieuse. (Soulignons au passage que l’antagonisme (!) Ville-Campagne n’en est qu’une conséquence.) De quoi parlait-on en disant cela (Marx comme les autres) ? On n’avait en vue que des hommes ÉGALEMENT RAISONNABLES (spiritualistes), en déplorant que les uns étaient Instruits, alors que les autres – la masse – étaient réduits à n’être qu’intelligents. Du coup, on promettait que le Socialisme ferait des ouvriers des Polytechniciens, des Ingénieurs sur le modèle Thermidorien, tels Lazare Carnot et Cie ! Et cela parce que le machinisme démocratisé laisserait aux prolétaires des loisirs leur permettant… de s’embourgeoiser à tout va ! Quand on pense que Lénine lui-même donnait en exemple le Fordisme et le Taylorisme… Le Comm-Anar tourne le dos à tout cela ; précisément parce qu’il lui faut une Technique… Matérialiste (récupérant l’approche de la Nature qui était celle de la société Parentale) ! Ce ne sont pas des “petits-bourgeois”, ni des Koulaks ou des Tsaristes, qui ont renversé Staline – sans coup férir ! –, mais de francs barbares, du type de “<b>l’ingénieur</b>” Boulganine, allié à des prétoriens tel le Maréchal Joukov, tous hauts dignitaires du Parti… Aucun “marxiste-léniniste” n’a encore compris cela.</p>
<p>Le travail Comm-Anar devra affronter bien des difficultés liées à l’héritage du <b>Parasitisme</b> à l’intérieur de la République Syndicale, et son maintien hors de ses “frontières”. Ce sont là de réels gros problèmes, et pourtant pas fondamentaux. Combien de temps mit la “République Chrétienne” à éliminer les dernières traces de l’esclavage direct antique en son sein ! Nous savons qu’en répudiant l’argent par “principe”, il y aura des obstacles sérieux dans la pratique. Ainsi :</p>
<p>- Que faire, sans “devise convertible” dans le commerce extérieur ?</p>
<p>- Comment enrayer tous les tripotages possibles autour des “avantages en nature” ?</p>
<p>Les vraies difficultés ne viennent pas de ce côté, mais de l’extinction effective de l’<b>Esclavage</b> antérieur de la société Politique (le “capitalisme” civilisateur), que nous n’avons plus le droit de diaboliser. Pourquoi Lénine parle-t-il si à la légère du “capitalisme maudit” (la Grande Initiative) ? Il devra bien adopter la N.E.P. moins de deux ans plus tard, préconiser une “construction du socialisme qui utilise le marché, le commerce et la circulation monétaire”…</p>
<p>Comment la République Syndicale maîtrisera-t-elle l’attribution du “salaire de luxe” d’un ministre, d’un général (même de milice)… et celle d’un ambassadeur en territoire barbare ? Faire surveiller ces hauts placés par un “commissaire politique” ? Incorporer dans leur charge celle de “tuteur” de deux élèves les suivant partout, désignés d’en bas, l’un surdoué et l’autre analphabète, de sorte qu’un candidat de ce genre, formé ailleurs, prenne leur place au bout de 2 ou 3 ans, reléguant l’ancien “spécialiste” au rang de conseiller ? On trouvera bien des formules !</p>
<p>Là où ça coince le plus, c’est mon idée de BONS NOMINATIFS. Est-ce une mauvaise piste ? De quelle manière les libeller en “temps continu” ? Et si on y parvient, pourra-t-on “épargner” ces bons, c’est-à-dire les “accumuler” ? Pour en faire quoi ?</p>
<p>Je continue ma recherche !</p>
<p style="text-align:center;"><b>•••</b></p>
<p>Quelques points sont certains :</p>
<p>Il faut, <b>dès le départ</b> de la République Syndicale, introduire au moins le germe de Volontariat-Gratuité. Un vrai germe. Pas un faux semblant du genre du “bol de fer” fonctionnariste.</p>
<p>Tout ce qui ressemble à des “<b>samedis communistes</b>” ne vaut rien du tout, est hors de propos. C’est une mesure étroitement propre à la société Politique en période révolutionnaire, de sorte que, à côté de l’héroïsme altruiste, sévissent également le marché noir et le sabotage.</p>
<p>La “<b>participation des cadres au travail manuel</b>”, les “points-travail” et leurs barèmes, les “fournitures gratuites”, etc., sont bien intentionnés, mais ne donnent rien si l’on garde le cadre de la vieille Productivité en temps discret et le culte de la Technique “bourgeoise”.</p>
<p><b>L’Église Réaliste</b>, QUANT À ELLE, doit maintenir sous la République Syndicale son “choix stratégique : mépris du pouvoir et avidité d’influence” (Livret : Décret N° 0, ch. 6, § 2). Plus que jamais ! Elle aura sérieusement contribué à l’avènement du nouveau régime. Mais le peuple au pouvoir – enfin ! – connaîtra bien des turbulences. Julien l’Apostat survint 25 ans après la mort de Constantin. Et le peuple, c’est FRONT-Église : l’attitude du Front vis-à-vis de l’Église sera bien sinueuse ! Bref, après la victoire, nous pouvons avoir à souffrir – passagèrement – PLUS que sous notre Barbarie. Il va falloir donc, si l’Église veut rester Église, qu’elle sache se maintenir contre vents et marées. Et se maintenir en s’imposant pour elle-même intégralement le régime de Volontariat-Gratuité. Les moines du Moyen-âge en étaient bien capables ! Serions-nous inférieurs à eux ?… Comment accorderons-nous notre Comm-Anar intégral avec la politique du Front <b>au pouvoir</b> ?…</p>
<p>(...)</p>

<p>__________________________</p>

				  

				  <p>Voir <a href="https://www.eglise-realiste.org/pdf/Travail_du_Comm-Anar_ed.pdf" target="_blank"> "Travail du Comm-Anar"</a> - Talib Freddy - octobre 2005</p>


			</div>
			<div class="modal-footer">
			  <a href="#!" class="modal-close waves-effect waves-green btn-flat">Vu</a>
			</div>
		  </div>


		  